### ISSUE TITLE
Hosting request for the updated content of bio-medical-and-signal-processing-laboratory - COEP

### ISSUE THREAD

**Issue by sushilmedhe** [Virtual-Labs/engineers-forum#230]
Please host the lab.
Link is given below.

https://github.com/Virtual-Labs/bio-medical-and-signal-processing-laboratory-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe The requested lab has been hosted with the updated content. Please follow the URL : http://bmsp-coep.vlabs.ac.in/

**Comment by sushilmedhe** [comment]
The lab is modified again. Please host the lab.

https://github.com/Virtual-Labs/bio-medical-and-signal-processing-laboratory-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe The modified lab has been hosted. Please follow the URL : http://bmsp-coep.vlabs.ac.in/

**Comment by sushilmedhe** [comment]
@sanchita-dixit Lab contents are reflected properly. but check the issue of url for this lab from COEP lab list (http://vlabs.ac.in/pune-labs.html) It display 404 not found. Check the url of the lab it is different. Please sort it out.

**Comment by sushilmedhe** [comment]
@sanchita-dixit Please re-host the lab again due to pre test and post test changes. link is given below.

https://github.com/Virtual-Labs/bio-medical-and-signal-processing-laboratory-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe Regarding redirection of the lab to an error page, a person is assigned this task of cross-checking and updating all the links on the vlabs landing page and the above mentioned lab is also on the list. It might take few days to update this link for your as a sequence is being followed for the same. If you need it urgently, we could try doing it on a priority basis.

The re-hosting would be done at the earliest.

**Comment by sushilmedhe** [comment]
@sanchita-dixit Try to do update link ASAP. and Re-host the lab now so it will be reflected to the test page. As it can be accessed from department so one can go through this and use it.

**Comment by sanchita-dixit** [comment]
@sushilmedhe The lab has been re-hosted. Please follow the URL : http://bmsp-coep.vlabs.ac.in
The URL is also redirected to the correct page. Now it is not leading to 404 error page. The pre and post conditions are still not working as per verification. Please confirm.

**Comment by sushilmedhe** [comment]
@sanchita-dixit The URL is redirected to correct page now. But the lab which you have hosted is not the one which I have updated on github yesterday. The hosted lab have previous github code. I had made changes in pre test and post test which are not reflected. Kindly remove previous container for this lab and try again. The updated code is not used from github for hosted lab.

**Comment by sanchita-dixit** [comment]
@sushilmedhe I have cloned the latest repo only yesterday. I verified your last commit and then only cloned the repository while re-hosting. I will try again once more. It was indeed strange to see that the changes didn't reflect after re-hosting.

**Comment by sushilmedhe** [comment]
@sanchita-dixit Yes. Do it. beacuse I have check the button coding in pre test and post test the id and onclick function calls are from previous update. in current update I have changed the ID and onclick function names as well.

Refer the following images.
1) Code from Bio-medical lab experiment submit button
![screenshot from 2016-02-18 14 02 27](https://cloud.githubusercontent.com/assets/8788705/13137706/e2b1312a-d648-11e5-99de-01712280202c.png)

2) Check the code for submit button in industrial automation lab experiment. The same code is given for both labs.
![screenshot from 2016-02-18 14 03 06](https://cloud.githubusercontent.com/assets/8788705/13137728/fa825432-d648-11e5-82db-28844db07d6c.png)

The submit button code is similar for both lab. In bio-medical lab the same code must be reflected.
Check out once.

**Comment by sanchita-dixit** [comment]
@sushilmedhe I tried doing it again but it is still running the old code in the browser. We tried and look into the code as per above snapshots, but couldn't figure the cause for this. We can't go through the entire code to debug the issue. You are requested to go through the code once and find any issue which could resolve this.

**Comment by sushilmedhe** [comment]
@sanchita-dixit  Please re-host the lab with the updated UI to 3.0. 
Link is given below

https://github.com/Virtual-Labs/bio-medical-and-signal-processing-laboratory-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe I re-hosted the requested lab but the UI is not appropriate after deployment. I have reverted back to older version. Below is the attached screenshot for the same.
![bmsp labui 3 0](https://cloud.githubusercontent.com/assets/13132618/13667477/89a22676-e6dc-11e5-88f1-ce59b3183d91.png)

**Comment by sushilmedhe** [comment]
@sanchita-dixit I have replaced the index.html file with the new one. can you please check once again by hosting the lab. It should work now. Please do re-hosting again.

link is given below
https://github.com/Virtual-Labs/bio-medical-and-signal-processing-laboratory-coep

**Comment by sanchita-dixit** [comment]
@sushilmedhe It is still showing the same screen as attached before.

**Comment by sivashankerN** [comment]
@sushilmedhe ,How can you close this issue without solving the issue. As per your request @sanchita-dixit updated sources and it is not as we expected and the screenshot also attached in the previous comment. Please look at the screenshot.

@sushilmedhe  that means, current lab sources that are at https://github.com/Virtual-Labs/bio-medical-and-signal-processing-laboratory-coep are incorrect.

This is the error while hosting the lab using ADS

>  File does not exist: /var/www/js/custom.js, referer: http://bmsp-coep.edx.vlabs.ac.in/
[Tue Oct 04 13:58:34 2016] [error] [client 10.100.1.7] File does not exist: /var/www/vendors, referer: http://bmsp-coep.vlabs.ac.in/
[Tue Oct 04 13:58:34 2016] [error] [client 10.100.1.7] File does not exist: /var/www/images/social, referer: http://bmsp-coep.vlabs.ac.in/
[Tue Oct 04 13:58:34 2016] [error] [client 10.100.1.7] File does not exist: /var/www/images/logo-new.png, referer: http://bmsp-coep.vlabs.ac.in/
[Tue Oct 04 13:58:34 2016] [error] [client 10.100.1.7] File does not exist: /var/www/images/social, referer: http://bmsp-coep.vlabs.ac.in/
[Tue Oct 04 13:58:34 2016] [error] [client 10.100.1.7] File does not exist: /var/www/js/jquery.js, referer: http://bmsp-coep.vlabs.ac.in/
[Tue Oct 04 13:58:34 2016] [error] [client 10.100.1.7] File does not exist: /var/www/js/bootstrap.min.js, referer: http://bmsp-coep.vlabs.ac.in/
[Tue Oct 04 13:58:34 2016] [error] [client 10.100.1.7] File does not exist: /var/www/js/custom.js, referer: http://bmsp-coep.vlabs.ac.in/
[Tue Oct 04 13:58:34 2016] [error] [client 10.100.1.7] File does not exist: /var/www/images/footer.png, referer: http://bmsp-coep.vlabs.ac.in/
[Tue Oct 04 13:58:34 2016] [error] [client 10.100.1.7] File does not exist: /var/www/vendors, referer: http://bmsp-coep.vlabs.ac.in/

**Comment by sivashankerN** [comment]
Please re-open this issue and don't close until this issue is resolved.
